# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, confloat, constr


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class SubjectGroupVar(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    var: str = Field(
        ...,
        description="Enter the subject group name exactly as it appears in EarthRanger (case-sensitive).",
        title="Subject Group Name",
    )


class SubjectGroup(BaseModel):
    subject_group_var: Optional[SubjectGroupVar] = Field(None, title="")


class CustomTrajsFilter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    min_length_meters: Optional[float] = Field(
        0.001,
        description="Discard segments shorter than this distance. Helps remove GPS noise and stationary fixes.",
        title="Minimum Segment Length (m)",
    )
    max_length_meters: Optional[float] = Field(
        5000,
        description="Discard segments longer than this distance. Helps remove unrealistic long-distance jumps.",
        title="Maximum Segment Length (m)",
    )
    min_time_secs: Optional[float] = Field(
        1,
        description="Discard segments with a duration shorter than this (in seconds).",
        title="Minimum Segment Duration (s)",
    )
    max_time_secs: Optional[float] = Field(
        21600,
        description="Discard segments with a duration longer than this (in seconds). Default is 6 hours (21,600 s).",
        title="Maximum Segment Duration (s)",
    )
    min_speed_kmhr: Optional[float] = Field(
        0.01,
        description="Discard segments where average speed falls below this value.",
        title="Minimum Speed (km/h)",
    )
    max_speed_kmhr: Optional[float] = Field(
        9.0,
        description="Discard segments where average speed exceeds this value. For elephants, 9 km/h is a sensible ceiling.",
        title="Maximum Speed (km/h)",
    )


class TrajectorySegmentFilter(BaseModel):
    custom_trajs_filter: Optional[CustomTrajsFilter] = Field(None, title="")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class PreviousPeriodType(str, Enum):
    Same_as_current_period = "Same as current period"
    Previous_month = "Previous month"
    Previous_3_months = "Previous 3 months"
    Previous_6_months = "Previous 6 months"
    Previous_year = "Previous year"


class PreviousTimeRange(BaseModel):
    since: datetime = Field(
        ..., description="The start time of the previous period", title="Since"
    )
    timezone: Optional[TimezoneInfo] = Field(
        default_factory=lambda: TimezoneInfo.model_validate(
            {"label": "UTC", "tzCode": "UTC", "name": "UTC", "utc": "+00:00"}
        ),
        description="Timezone (defaults to UTC)",
    )
    time_format: Optional[str] = Field(
        "%d %b %Y %H:%M:%S", description="The time format", title="Time Format"
    )


class PreviousTimeRangeOption(BaseModel):
    time_range: PreviousTimeRange


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class GoogleEarthEngineConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class FeatureSetQuery(BaseModel):
    featureset_name: constr(min_length=1) = Field(
        ...,
        description="Display name of the featureset exactly as it appears in EarthRanger e.g. 'Boundaries'.",
        title="Featureset Name",
    )


class LandDxOverlayOption(BaseModel):
    pass


class LineStyle(BaseModel):
    color: Optional[List[str]] = Field(
        [],
        description="Line hex colour(s) e.g. ['#E63946']. Cycles across rows.",
        title="Color",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1.0, description="Line opacity 0–1.", title="Opacity"
    )
    width: Optional[float] = Field(
        2.0, description="Line width in pixels.", title="Width"
    )


class PointStyle(BaseModel):
    color: Optional[List[str]] = Field(
        [],
        description="Fill hex colour(s). For SVG icons this tints the marker. Cycles across rows.",
        title="Color",
    )
    size: Optional[float] = Field(
        None,
        description="Point radius / icon size in pixels. Leave empty to use the size set in EarthRanger.",
        title="Size",
    )


class PolygonStyle(BaseModel):
    fill_color: Optional[List[str]] = Field(
        [],
        description="Fill hex colour(s) e.g. ['#FFA500']. Cycles across rows.",
        title="Fill Color",
    )
    stroke_color: Optional[str] = Field(
        None, description="Border hex colour.", title="Stroke Color"
    )
    fill_opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1.0, description="Fill opacity 0–1.", title="Fill Opacity"
    )
    stroke_width: Optional[float] = Field(
        2.0, description="Border width in pixels.", title="Stroke Width"
    )


class DownloadFile(BaseModel):
    url: str = Field(..., description="URL to download a file", title="URL")


class LocalFile(BaseModel):
    file_path: str = Field(
        ..., description="Path to a local file", title="Local file path"
    )


class ValueGrouper(BaseModel):
    index_name: Optional[str] = None


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")
    time_format: Optional[str] = Field(
        "%d %b %Y %H:%M:%S", description="The time format", title="Time Format"
    )


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class GeeProjectName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: GoogleEarthEngineConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class LogoPath(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    input_method: Union[DownloadFile, LocalFile] = Field(
        ...,
        description="Provide the organization logo to display on the report cover page (PNG or JPG recommended).",
        title="Input Method",
    )


class ReportLogo(BaseModel):
    logo_path: Optional[LogoPath] = Field(None, title="")


class PreviousCustomTimeRangeOption(BaseModel):
    custom: PreviousPeriodType = Field(
        ..., description="Select the previous period type"
    )


class LayerStyle(BaseModel):
    polygon: Optional[List[PolygonStyle]] = Field(
        [],
        description="Polygon styling. Add one entry to override ER native colours.",
        max_length=1,
        title="Polygon",
    )
    line: Optional[List[LineStyle]] = Field(
        [],
        description="Line styling. Add one entry to override ER native colours.",
        max_length=1,
        title="Line",
    )
    point: Optional[List[PointStyle]] = Field(
        [],
        description="Point and icon marker styling. Add one entry to override ER native colours.",
        max_length=1,
        title="Point",
    )


class SetPreviousPeriod(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    option: Union[PreviousCustomTimeRangeOption, PreviousTimeRangeOption] = Field(
        ..., title="Option"
    )


class SetPreviousPeriodRange(BaseModel):
    set_previous_period: Optional[SetPreviousPeriod] = Field(None, title="")


class FeatureIdQuery(BaseModel):
    feature_id: str = Field(
        ...,
        description="UUID of a specific spatial feature available on EarthRanger.",
        title="Feature Id",
    )
    style: Optional[List[LayerStyle]] = Field(
        [],
        description="Optional: Override how EarthRanger spatial features are rendered on the map. If not specified, features will use their native EarthRanger colours and styling.",
        max_length=1,
        title="Style",
    )


class FeatureTypeQuery(BaseModel):
    feature_type: constr(min_length=1) = Field(
        ...,
        description="Feature type name as shown in EarthRanger e.g. 'Conservancy'.",
        title="Feature Type",
    )
    style: Optional[List[LayerStyle]] = Field(
        [],
        description="Optional: Override how EarthRanger spatial features are rendered on the map. If not specified, features will use their native EarthRanger colours and styling.",
        max_length=1,
        title="Style",
    )


class EarthRangerSource(BaseModel):
    query: Optional[Union[FeatureSetQuery, FeatureTypeQuery, FeatureIdQuery]] = Field(
        None, title="Query"
    )


class ERSpatialFeatureOverlayOption(BaseModel):
    source: Optional[EarthRangerSource] = Field(
        None,
        description="Configure the EarthRanger spatial feature query.",
        title="Source",
    )
    legend_title: Optional[str] = Field(
        "Legend", description="Label shown in the map legend.", title="Legend Title"
    )
    fill_opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        0.35,
        description="Fill opacity for polygon interiors. Set to 0 to show outlines only.",
        title="Fill Opacity",
    )
    line_opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        0.75,
        description="Opacity of polygon borders from 0 (transparent) to 1 (fully opaque).",
        title="Line Opacity",
    )


class MapOverlay1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    option: Union[LandDxOverlayOption, ERSpatialFeatureOverlayOption] = Field(
        ...,
        description="Select the overlay source to display on all maps.",
        title="Option",
    )


class MapOverlay(BaseModel):
    map_overlay: Optional[MapOverlay1] = Field(None, title="")


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set workflow details",
    )
    time_range: Optional[TimeRange] = Field(
        None,
        description="Choose the period of time to analyze.",
        title="Define analysis time range",
    )
    Set_previous_period_range: Optional[SetPreviousPeriodRange] = Field(
        None,
        alias="Set previous period range",
        description='Define the previous period for comparison. By default, it will match the current period, but you can choose predefined options like "Previous month" or "Previous year", or specify a custom range.',
    )
    er_client_name: Optional[ErClientName] = Field(
        None, title="Connect to earth ranger"
    )
    gee_project_name: Optional[GeeProjectName] = Field(
        None, title="Connect to earth engine"
    )
    Subject_Group: Optional[SubjectGroup] = Field(
        None, alias="Subject Group", description="Choose subject group to analyze"
    )
    Map_Overlay: Optional[MapOverlay] = Field(
        None,
        alias="Map Overlay",
        description="Choose the overlay to display on all maps: (a) LandDx — standard protected areas downloaded automatically; (b) EarthRanger Spatial Feature — fetch a named feature set from EarthRanger.",
    )
    Trajectory_Segment_Filter: Optional[TrajectorySegmentFilter] = Field(
        None,
        alias="Trajectory Segment Filter",
        description="Filter trajectory segments based on criteria like minimum/maximum length, duration and speed. This helps remove GPS noise and unrealistic movements. The same filter will be applied to both current and previous trajectories to ensure consistency in the analysis.",
    )
    Report_logo: Optional[ReportLogo] = Field(
        None,
        alias="Report logo",
        description="Download or fetch the logo to be used in the report cover page. This task can be customized to fetch logos from different sources based on user requirements.",
    )
