# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class SubjectGroupVar(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    var: str = Field(
        ...,
        description="Enter the subject group name exactly as it appears in EarthRanger (case-sensitive).",
        title="Subject Group Name",
    )


class SubjectGroup(BaseModel):
    subject_group_var: Optional[SubjectGroupVar] = Field(None, title="")


class CustomTrajsFilter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    min_length_meters: Optional[float] = Field(
        0.001,
        description="Discard segments shorter than this distance. Helps remove GPS noise and stationary fixes.",
        title="Minimum Segment Length (m)",
    )
    max_length_meters: Optional[float] = Field(
        5000,
        description="Discard segments longer than this distance. Helps remove unrealistic long-distance jumps.",
        title="Maximum Segment Length (m)",
    )
    min_time_secs: Optional[float] = Field(
        1,
        description="Discard segments with a duration shorter than this (in seconds).",
        title="Minimum Segment Duration (s)",
    )
    max_time_secs: Optional[float] = Field(
        21600,
        description="Discard segments with a duration longer than this (in seconds). Default is 6 hours (21,600 s).",
        title="Maximum Segment Duration (s)",
    )
    min_speed_kmhr: Optional[float] = Field(
        0.01,
        description="Discard segments where average speed falls below this value.",
        title="Minimum Speed (km/h)",
    )
    max_speed_kmhr: Optional[float] = Field(
        9.0,
        description="Discard segments where average speed exceeds this value. For elephants, 9 km/h is a sensible ceiling.",
        title="Maximum Speed (km/h)",
    )


class TrajectorySegmentFilter(BaseModel):
    custom_trajs_filter: Optional[CustomTrajsFilter] = Field(None, title="")


class ZoomToEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    expansion_factor: Optional[float] = Field(
        1.05,
        description="Adds padding around the map boundary. 1.0 = tight fit, 1.05 = 5% padding (default), 1.2 = 20% padding.",
        title="Expansion Factor",
    )


class ZoomToGdfExtent(BaseModel):
    zoom_to_envelope: Optional[ZoomToEnvelope] = Field(None, title="")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class PreviousPeriodType(str, Enum):
    Same_as_current_period = "Same as current period"
    Previous_month = "Previous month"
    Previous_3_months = "Previous 3 months"
    Previous_6_months = "Previous 6 months"
    Previous_year = "Previous year"


class PreviousTimeRange(BaseModel):
    since: datetime = Field(
        ..., description="The start time of the previous period", title="Since"
    )
    timezone: Optional[TimezoneInfo] = Field(
        default_factory=lambda: TimezoneInfo.model_validate(
            {"label": "UTC", "tzCode": "UTC", "name": "UTC", "utc": "+00:00"}
        ),
        description="Timezone (defaults to UTC)",
    )
    time_format: Optional[str] = Field(
        "%d %b %Y %H:%M:%S", description="The time format", title="Time Format"
    )


class PreviousTimeRangeOption(BaseModel):
    time_range: PreviousTimeRange


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class GoogleEarthEngineConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class DownloadFile(BaseModel):
    url: str = Field(..., description="URL to download a file", title="URL")


class LocalFile(BaseModel):
    file_path: str = Field(
        ..., description="Path to a local file", title="Local file path"
    )


class ValueGrouper(BaseModel):
    index_name: Optional[str] = None


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")
    time_format: Optional[str] = Field(
        "%d %b %Y %H:%M:%S", description="The time format", title="Time Format"
    )


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class GeeProjectName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: GoogleEarthEngineConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class RetrieveLdxDb(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    input_method: Union[DownloadFile, LocalFile] = Field(..., title="Input Method")


class LoadLandDxDatabase(BaseModel):
    retrieve_ldx_db: Optional[RetrieveLdxDb] = Field(None, title="")


class LogoPath(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    input_method: Union[DownloadFile, LocalFile] = Field(
        ...,
        description="Provide the organization logo to display on the report cover page (PNG or JPG recommended).",
        title="Input Method",
    )


class ReportLogo(BaseModel):
    logo_path: Optional[LogoPath] = Field(None, title="")


class PreviousCustomTimeRangeOption(BaseModel):
    custom: PreviousPeriodType = Field(
        ..., description="Select the previous period type"
    )


class SetPreviousPeriod(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    option: Union[PreviousCustomTimeRangeOption, PreviousTimeRangeOption] = Field(
        ..., title="Option"
    )


class SetPreviousPeriodRange(BaseModel):
    set_previous_period: Optional[SetPreviousPeriod] = Field(None, title="")


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set workflow details",
    )
    time_range: Optional[TimeRange] = Field(
        None,
        description="Choose the period of time to analyze.",
        title="Define analysis time range",
    )
    Set_previous_period_range: Optional[SetPreviousPeriodRange] = Field(
        None,
        alias="Set previous period range",
        description='Define the previous period for comparison. By default, it will match the current period, but you can choose predefined options like "Previous month" or "Previous year", or specify a custom range.',
    )
    er_client_name: Optional[ErClientName] = Field(
        None, title="Connect to earth ranger"
    )
    gee_project_name: Optional[GeeProjectName] = Field(
        None, title="Connect to earth engine"
    )
    Subject_Group: Optional[SubjectGroup] = Field(
        None, alias="Subject Group", description="Choose subject group to analyze"
    )
    Load_landDx_database: Optional[LoadLandDxDatabase] = Field(
        None,
        alias="Load landDx database",
        description="Load the landDx geodatabase and prepare it for mapping. The geodatabase will be filtered to include only protected areas (Community Conservancies, National Reserves, National Parks) and styled for visualization.",
    )
    Trajectory_Segment_Filter: Optional[TrajectorySegmentFilter] = Field(
        None,
        alias="Trajectory Segment Filter",
        description="Filter trajectory segments based on criteria like minimum/maximum length, duration and speed. This helps remove GPS noise and unrealistic movements. The same filter will be applied to both current and previous trajectories to ensure consistency in the analysis.",
    )
    Zoom_to_gdf_extent: Optional[ZoomToGdfExtent] = Field(
        None,
        alias="Zoom to gdf extent",
        description="Calculate the geographic extent of the movement tracks and determine an appropriate zoom level and center point for the map. This ensures that all tracks are visible and well-framed when the map is rendered.",
    )
    Report_logo: Optional[ReportLogo] = Field(
        None,
        alias="Report logo",
        description="Download or fetch the logo to be used in the report cover page. This task can be customized to fetch logos from different sources based on user requirements.",
    )
