# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class SubjectGroupVar(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    var: str = Field(..., title="")


class CustomTrajsFilter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    min_length_meters: Optional[float] = Field(0.001, title="Min Length Meters")
    max_length_meters: Optional[float] = Field(5000, title="Max Length Meters")
    min_time_secs: Optional[float] = Field(1, title="Min Time Secs")
    max_time_secs: Optional[float] = Field(21600, title="Max Time Secs")
    min_speed_kmhr: Optional[float] = Field(0.01, title="Min Speed Kmhr")
    max_speed_kmhr: Optional[float] = Field(9.0, title="Max Speed Kmhr")


class ZoomToEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    expansion_factor: Optional[float] = Field(
        1.05,
        description="Factor to expand the bounding box (e.g., 1.2 = 20% larger)",
        title="Expansion Factor",
    )


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class PreviousPeriodType(str, Enum):
    Same_as_current_period = "Same as current period"
    Previous_month = "Previous month"
    Previous_3_months = "Previous 3 months"
    Previous_6_months = "Previous 6 months"
    Previous_year = "Previous year"


class PreviousTimeRange(BaseModel):
    since: datetime = Field(
        ..., description="The start time of the previous period", title="Since"
    )
    timezone: Optional[TimezoneInfo] = Field(
        default_factory=lambda: TimezoneInfo.model_validate(
            {"label": "UTC", "tzCode": "UTC", "name": "UTC", "utc": "+00:00"}
        ),
        description="Timezone (defaults to UTC)",
    )
    time_format: Optional[str] = Field(
        "%d %b %Y %H:%M:%S", description="The time format", title="Time Format"
    )


class PreviousTimeRangeOption(BaseModel):
    time_range: PreviousTimeRange


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class GoogleEarthEngineConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class DownloadFile(BaseModel):
    url: str = Field(..., description="URL to download a file", title="URL")


class LocalFile(BaseModel):
    file_path: str = Field(
        ..., description="Path to a local file", title="Local file path"
    )


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")
    time_format: Optional[str] = Field(
        "%d %b %Y %H:%M:%S", description="The time format", title="Time Format"
    )


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class GeeProjectName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: GoogleEarthEngineConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class RetrieveLdxDb(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    input_method: Union[DownloadFile, LocalFile] = Field(..., title="Input Method")


class LogoPath(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    input_method: Union[DownloadFile, LocalFile] = Field(..., title="Input Method")


class PreviousCustomTimeRangeOption(BaseModel):
    custom: PreviousPeriodType = Field(
        ..., description="Select the previous period type"
    )


class SetPreviousPeriod(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    option: Union[PreviousCustomTimeRangeOption, PreviousTimeRangeOption] = Field(
        ..., title="Option"
    )


class Params(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set workflow details",
    )
    time_range: Optional[TimeRange] = Field(
        None,
        description="Choose the period of time to analyze.",
        title="Define analysis time range",
    )
    set_previous_period: Optional[SetPreviousPeriod] = Field(None, title="")
    er_client_name: Optional[ErClientName] = Field(
        None, title="Connect to earth ranger"
    )
    gee_project_name: Optional[GeeProjectName] = Field(
        None, title="Connect to earth engine"
    )
    subject_group_var: Optional[SubjectGroupVar] = Field(None, title="")
    retrieve_ldx_db: Optional[RetrieveLdxDb] = Field(None, title="")
    custom_trajs_filter: Optional[CustomTrajsFilter] = Field(None, title="")
    zoom_to_envelope: Optional[ZoomToEnvelope] = Field(None, title="")
    logo_path: Optional[LogoPath] = Field(None, title="")
