# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, confloat, constr


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class SubjectGroupVar(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    var: str = Field(..., title="")


class CustomTrajsFilter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    min_length_meters: Optional[float] = Field(0.001, title="Min Length Meters")
    max_length_meters: Optional[float] = Field(5000, title="Max Length Meters")
    min_time_secs: Optional[float] = Field(1, title="Min Time Secs")
    max_time_secs: Optional[float] = Field(21600, title="Max Time Secs")
    min_speed_kmhr: Optional[float] = Field(0.01, title="Min Speed Kmhr")
    max_speed_kmhr: Optional[float] = Field(9.0, title="Max Speed Kmhr")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class PreviousPeriodType(str, Enum):
    Same_as_current_period = "Same as current period"
    Previous_month = "Previous month"
    Previous_3_months = "Previous 3 months"
    Previous_6_months = "Previous 6 months"
    Previous_year = "Previous year"


class PreviousTimeRange(BaseModel):
    since: datetime = Field(
        ..., description="The start time of the previous period", title="Since"
    )
    timezone: Optional[TimezoneInfo] = Field(
        default_factory=lambda: TimezoneInfo.model_validate(
            {"label": "UTC", "tzCode": "UTC", "name": "UTC", "utc": "+00:00"}
        ),
        description="Timezone (defaults to UTC)",
    )
    time_format: Optional[str] = Field(
        "%d %b %Y %H:%M:%S", description="The time format", title="Time Format"
    )


class PreviousTimeRangeOption(BaseModel):
    time_range: PreviousTimeRange


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class GoogleEarthEngineConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class FeatureSetQuery(BaseModel):
    featureset_name: constr(min_length=1) = Field(
        ...,
        description="Display name of the featureset exactly as it appears in EarthRanger e.g. 'Boundaries'.",
        title="Featureset Name",
    )


class LandDxOverlayOption(BaseModel):
    pass


class LineStyle(BaseModel):
    color: Optional[List[str]] = Field(
        [],
        description="Line hex colour(s) e.g. ['#E63946']. Cycles across rows.",
        title="Color",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1.0, description="Line opacity 0–1.", title="Opacity"
    )
    width: Optional[float] = Field(
        2.0, description="Line width in pixels.", title="Width"
    )


class PointStyle(BaseModel):
    color: Optional[List[str]] = Field(
        [],
        description="Fill hex colour(s). For SVG icons this tints the marker. Cycles across rows.",
        title="Color",
    )
    size: Optional[float] = Field(
        None,
        description="Point radius / icon size in pixels. Leave empty to use the size set in EarthRanger.",
        title="Size",
    )


class PolygonStyle(BaseModel):
    fill_color: Optional[List[str]] = Field(
        [],
        description="Fill hex colour(s) e.g. ['#FFA500']. Cycles across rows.",
        title="Fill Color",
    )
    stroke_color: Optional[str] = Field(
        None, description="Border hex colour.", title="Stroke Color"
    )
    fill_opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1.0, description="Fill opacity 0–1.", title="Fill Opacity"
    )
    stroke_width: Optional[float] = Field(
        2.0, description="Border width in pixels.", title="Stroke Width"
    )


class DownloadFile(BaseModel):
    url: str = Field(..., description="URL to download a file", title="URL")


class LocalFile(BaseModel):
    file_path: str = Field(
        ..., description="Path to a local file", title="Local file path"
    )


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")
    time_format: Optional[str] = Field(
        "%d %b %Y %H:%M:%S", description="The time format", title="Time Format"
    )


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class GeeProjectName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: GoogleEarthEngineConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class LogoPath(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    input_method: Union[DownloadFile, LocalFile] = Field(..., title="Input Method")


class PreviousCustomTimeRangeOption(BaseModel):
    custom: PreviousPeriodType = Field(
        ..., description="Select the previous period type"
    )


class LayerStyle(BaseModel):
    polygon: Optional[List[PolygonStyle]] = Field(
        [],
        description="Polygon styling. Add one entry to override ER native colours.",
        max_length=1,
        title="Polygon",
    )
    line: Optional[List[LineStyle]] = Field(
        [],
        description="Line styling. Add one entry to override ER native colours.",
        max_length=1,
        title="Line",
    )
    point: Optional[List[PointStyle]] = Field(
        [],
        description="Point and icon marker styling. Add one entry to override ER native colours.",
        max_length=1,
        title="Point",
    )


class SetPreviousPeriod(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    option: Union[PreviousCustomTimeRangeOption, PreviousTimeRangeOption] = Field(
        ..., title="Option"
    )


class FeatureIdQuery(BaseModel):
    feature_id: str = Field(
        ...,
        description="UUID of a specific spatial feature available on EarthRanger.",
        title="Feature Id",
    )
    style: Optional[List[LayerStyle]] = Field(
        [],
        description="Optional: Override how EarthRanger spatial features are rendered on the map. If not specified, features will use their native EarthRanger colours and styling.",
        max_length=1,
        title="Style",
    )


class FeatureTypeQuery(BaseModel):
    feature_type: constr(min_length=1) = Field(
        ...,
        description="Feature type name as shown in EarthRanger e.g. 'Conservancy'.",
        title="Feature Type",
    )
    style: Optional[List[LayerStyle]] = Field(
        [],
        description="Optional: Override how EarthRanger spatial features are rendered on the map. If not specified, features will use their native EarthRanger colours and styling.",
        max_length=1,
        title="Style",
    )


class EarthRangerSource(BaseModel):
    query: Optional[Union[FeatureSetQuery, FeatureTypeQuery, FeatureIdQuery]] = Field(
        None, title="Query"
    )


class ERSpatialFeatureOverlayOption(BaseModel):
    source: Optional[EarthRangerSource] = Field(
        None,
        description="Configure the EarthRanger spatial feature query.",
        title="Source",
    )
    legend_title: Optional[str] = Field(
        "Legend", description="Label shown in the map legend.", title="Legend Title"
    )
    fill_opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        0.35,
        description="Fill opacity for polygon interiors. Set to 0 to show outlines only.",
        title="Fill Opacity",
    )
    line_opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        0.75,
        description="Opacity of polygon borders from 0 (transparent) to 1 (fully opaque).",
        title="Line Opacity",
    )


class MapOverlay(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    option: Union[LandDxOverlayOption, ERSpatialFeatureOverlayOption] = Field(
        ...,
        description="Select the overlay source to display on all maps.",
        title="Option",
    )


class Params(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set workflow details",
    )
    time_range: Optional[TimeRange] = Field(
        None,
        description="Choose the period of time to analyze.",
        title="Define analysis time range",
    )
    set_previous_period: Optional[SetPreviousPeriod] = Field(None, title="")
    er_client_name: Optional[ErClientName] = Field(
        None, title="Connect to earth ranger"
    )
    gee_project_name: Optional[GeeProjectName] = Field(
        None, title="Connect to earth engine"
    )
    subject_group_var: Optional[SubjectGroupVar] = Field(None, title="")
    map_overlay: Optional[MapOverlay] = Field(None, title="")
    custom_trajs_filter: Optional[CustomTrajsFilter] = Field(None, title="")
    logo_path: Optional[LogoPath] = Field(None, title="")
